/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;
//t

import BusinessLayerPackage.Staff;
import BusinessLayerPackage.StaffRequest;
import DataAccessLayerPackage.StaffHandler;
import DataAccessLayerPackage.StaffRequestHandler;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class AdminOrders extends javax.swing.JFrame {

    /**
     * Creates new form AdminOrders
     */
    public AdminOrders() {
        initComponents();
        ArrayList<StaffRequest> staffRequests = StaffRequest.getStaffRequests(StaffRequestHandler.requestType.All, 0);
        populateTable(staffRequests);
        tblStaffRequests.setAutoCreateRowSorter(true);
    }

    private void populateTable(ArrayList<StaffRequest> requestList) {

        DefaultTableModel dmodel = (DefaultTableModel) tblStaffRequests.getModel();
        Object[] row = new Object[5];
        //get all staff
        ArrayList<Staff> allStaff = (new Staff()).getStaff(StaffHandler.staffType.All);
//        for (Staff s : allStaff) {
//                    System.out.println(s.toString());
//                }
        //clearTable
        dmodel.setRowCount(0);
        if (requestList.size() > 0) {
            for (StaffRequest stc : requestList) {
                row[0] = stc.getRequestNr();
                for (Staff s : allStaff) {
                    if (s.getUserID() == stc.getStaffID()) {

                        row[1] = s.getFirstName() + " " + s.getLastName();
                    }
                }
                row[2] = stc.getRequestDate().getDate();
                row[3] = stc.getRequestDate().getMonth() + 1;
                row[4] = stc.getRequestDate().getYear() + 1900;
                dmodel.addRow(row);
            }
        } else {
            JOptionPane.showMessageDialog(null, "There is no Data that matches your search result", "Attention", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewAllStaffReq = new javax.swing.JButton();
        btnViewComplStaffRequests = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnViewIncomStaffRequests = new javax.swing.JButton();
        lDay = new javax.swing.JLabel();
        spnDay = new javax.swing.JSpinner();
        btnSortByDate = new javax.swing.JButton();
        lYear = new javax.swing.JLabel();
        lMonth = new javax.swing.JLabel();
        spnYear = new javax.swing.JSpinner();
        spnMonth = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStaffRequests = new javax.swing.JTable();
        btnBackLogout = new javax.swing.JButton();
        btnMinimize = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1031, 665));
        setResizable(false);
        getContentPane().setLayout(null);

        btnViewAllStaffReq.setBackground(new java.awt.Color(254, 212, 29));
        btnViewAllStaffReq.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnViewAllStaffReq.setText("View All Requests");
        btnViewAllStaffReq.setToolTipText("View all requests from staff");
        btnViewAllStaffReq.setBorderPainted(false);
        btnViewAllStaffReq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewAllStaffReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllStaffReqActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewAllStaffReq);
        btnViewAllStaffReq.setBounds(110, 170, 150, 40);

        btnViewComplStaffRequests.setBackground(new java.awt.Color(254, 212, 29));
        btnViewComplStaffRequests.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnViewComplStaffRequests.setText("View Complete Requests");
        btnViewComplStaffRequests.setToolTipText("View completed requests from staff");
        btnViewComplStaffRequests.setBorderPainted(false);
        btnViewComplStaffRequests.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewComplStaffRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewComplStaffRequestsActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewComplStaffRequests);
        btnViewComplStaffRequests.setBounds(280, 170, 190, 40);

        jButton1.setText("Generate Report");
        getContentPane().add(jButton1);
        jButton1.setBounds(750, 520, 180, 40);

        btnViewIncomStaffRequests.setBackground(new java.awt.Color(254, 212, 29));
        btnViewIncomStaffRequests.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnViewIncomStaffRequests.setText("View Incomplete Requests");
        btnViewIncomStaffRequests.setToolTipText("View incomplete requests from staff");
        btnViewIncomStaffRequests.setBorderPainted(false);
        btnViewIncomStaffRequests.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewIncomStaffRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewIncomStaffRequestsActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewIncomStaffRequests);
        btnViewIncomStaffRequests.setBounds(490, 170, 220, 40);

        lDay.setText("Day");
        getContentPane().add(lDay);
        lDay.setBounds(730, 120, 21, 16);
        getContentPane().add(spnDay);
        spnDay.setBounds(730, 140, 50, 22);

        btnSortByDate.setText("Sort By Date");
        getContentPane().add(btnSortByDate);
        btnSortByDate.setBounds(730, 170, 190, 40);

        lYear.setText("Year");
        getContentPane().add(lYear);
        lYear.setBounds(850, 120, 26, 16);

        lMonth.setText("Month");
        getContentPane().add(lMonth);
        lMonth.setBounds(790, 120, 35, 16);
        getContentPane().add(spnYear);
        spnYear.setBounds(840, 140, 80, 22);
        getContentPane().add(spnMonth);
        spnMonth.setBounds(790, 140, 40, 22);

        tblStaffRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request", "Staff Name", "Day", "Month", "Year"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStaffRequests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStaffRequestsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStaffRequests);
        if (tblStaffRequests.getColumnModel().getColumnCount() > 0) {
            tblStaffRequests.getColumnModel().getColumn(0).setResizable(false);
            tblStaffRequests.getColumnModel().getColumn(1).setResizable(false);
            tblStaffRequests.getColumnModel().getColumn(2).setResizable(false);
            tblStaffRequests.getColumnModel().getColumn(3).setResizable(false);
            tblStaffRequests.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 240, 820, 280);

        btnBackLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnBackLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnBackLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        btnBackLogout.setToolTipText("Back");
        btnBackLogout.setBorder(null);
        btnBackLogout.setBorderPainted(false);
        btnBackLogout.setContentAreaFilled(false);
        btnBackLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackLogoutMouseClicked(evt);
            }
        });
        btnBackLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnBackLogout);
        btnBackLogout.setBounds(950, 10, 31, 31);

        btnMinimize.setBackground(new java.awt.Color(255, 255, 255));
        btnMinimize.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        btnMinimize.setToolTipText("Minimize");
        btnMinimize.setBorder(null);
        btnMinimize.setBorderPainted(false);
        btnMinimize.setContentAreaFilled(false);
        btnMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(btnMinimize);
        btnMinimize.setBounds(910, 10, 31, 31);

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        btnExit.setToolTipText("Exit");
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(980, 10, 50, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/orderMng.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1031, 637);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackLogoutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackLogoutMouseClicked

    private void btnBackLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackLogoutActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);;
        this.dispose();
    }//GEN-LAST:event_btnBackLogoutActionPerformed

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        int selection = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Please Note", JOptionPane.INFORMATION_MESSAGE);
        if (selection == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnViewIncomStaffRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewIncomStaffRequestsActionPerformed
        ArrayList<StaffRequest> staffRequests = StaffRequest.getStaffRequests(StaffRequestHandler.requestType.Incomplete, 0);
        populateTable(staffRequests);

    }//GEN-LAST:event_btnViewIncomStaffRequestsActionPerformed

    private void btnViewAllStaffReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllStaffReqActionPerformed
        ArrayList<StaffRequest> staffRequests = StaffRequest.getStaffRequests(StaffRequestHandler.requestType.All, 0);
        populateTable(staffRequests);
    }//GEN-LAST:event_btnViewAllStaffReqActionPerformed

    private void btnViewComplStaffRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewComplStaffRequestsActionPerformed
        ArrayList<StaffRequest> staffRequests = StaffRequest.getStaffRequests(StaffRequestHandler.requestType.Complete, 0);
        populateTable(staffRequests);
    }//GEN-LAST:event_btnViewComplStaffRequestsActionPerformed

    private void tblStaffRequestsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStaffRequestsMouseClicked
        //Get selected value
        //Send object to update form.
        DefaultTableModel dmodel = (DefaultTableModel) tblStaffRequests.getModel();
        StaffRequest curRequest = new StaffRequest();
        int CurrentPackage
                = ((int) tblStaffRequests.getValueAt(
                        tblStaffRequests.getSelectedRow(), 0));
        //check that it is an unmanaged package
        ArrayList<StaffRequest> staffRequests = StaffRequest.getStaffRequests(StaffRequestHandler.requestType.All, 0);
        boolean checkIncomplete = false;
        for (StaffRequest st : staffRequests) {
            if (CurrentPackage == st.getRequestNr() && st.getComplete() == 0) {
                checkIncomplete = true;
            }
        }
        if (checkIncomplete) {
            int selection = JOptionPane.showConfirmDialog(null, "Do you want to handle request " + CurrentPackage,
                    "Please Note", JOptionPane.INFORMATION_MESSAGE);
            if (selection == JOptionPane.YES_OPTION) {
                for (StaffRequest request : staffRequests) {
                    if (request.getRequestNr() == CurrentPackage) {
                        curRequest = request;
                    }
                }
                //new update page object
                AdminOrderCompletion newAdminOrderCompletion = new AdminOrderCompletion(curRequest);
                newAdminOrderCompletion.setVisible(true);;
                this.dispose();
            }
        }
    }//GEN-LAST:event_tblStaffRequestsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOrders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackLogout;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JButton btnSortByDate;
    private javax.swing.JButton btnViewAllStaffReq;
    private javax.swing.JButton btnViewComplStaffRequests;
    private javax.swing.JButton btnViewIncomStaffRequests;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lDay;
    private javax.swing.JLabel lMonth;
    private javax.swing.JLabel lYear;
    private javax.swing.JSpinner spnDay;
    private javax.swing.JSpinner spnMonth;
    private javax.swing.JSpinner spnYear;
    private javax.swing.JTable tblStaffRequests;
    // End of variables declaration//GEN-END:variables
}
