/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;
//t

import BusinessLayerPackage.Admin;
import BusinessLayerPackage.BCSerializer;
import BusinessLayerPackage.Reporter;
import BusinessLayerPackage.RequestDetails;
import BusinessLayerPackage.Staff;
import BusinessLayerPackage.StaffRequest;
import BusinessLayerPackage.Stock;
import DataAccessLayerPackage.StaffHandler;
import DataAccessLayerPackage.StaffRequestHandler;
import java.text.DateFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class AdminOrders extends javax.swing.JFrame {

    /**
     * Creates new form AdminOrders
     */
    public AdminOrders() {
        initComponents();
        ArrayList<StaffRequest> staffRequests = StaffRequest.getStaffRequests(StaffRequestHandler.requestType.All, 0);
        populateTable(staffRequests);
        tblStaffRequests.setAutoCreateRowSorter(true);
    }
    
    private void populateTable(ArrayList<StaffRequest> requestList) {
        
        DefaultTableModel dmodel = (DefaultTableModel) tblStaffRequests.getModel();
        Object[] row = new Object[5];
        //get all staff
        ArrayList<Staff> allStaff = (new Staff()).getStaff(StaffHandler.staffType.All);
//        for (Staff s : allStaff) {
//                    System.out.println(s.toString());
//                }
        //clearTable
        dmodel.setRowCount(0);
        if (requestList.size() > 0) {
            for (StaffRequest stc : requestList) {
                row[0] = stc.getRequestNr();
                for (Staff s : allStaff) {
                    if (s.getUserID() == stc.getStaffID()) {
                        
                        row[1] = s.getFirstName() + " " + s.getLastName();
                    }
                }
                row[2] = stc.getRequestDate().getDate();
                row[3] = stc.getRequestDate().getMonth() + 1;
                row[4] = stc.getRequestDate().getYear() + 1900;
                dmodel.addRow(row);
            }
        } else {
            JOptionPane.showMessageDialog(null, "There is no Data that matches your search result", "Attention", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewAllStaffReq = new javax.swing.JButton();
        btnViewComplStaffRequests = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnViewIncomStaffRequests = new javax.swing.JButton();
        lDay = new javax.swing.JLabel();
        spnDay = new javax.swing.JSpinner();
        btnSortByDate = new javax.swing.JButton();
        lYear = new javax.swing.JLabel();
        lMonth = new javax.swing.JLabel();
        spnYear = new javax.swing.JSpinner();
        spnMonth = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStaffRequests = new javax.swing.JTable();
        btnBackLogout = new javax.swing.JButton();
        btnMinimize = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        frameMove = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1030, 636));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        btnViewAllStaffReq.setBackground(new java.awt.Color(254, 212, 29));
        btnViewAllStaffReq.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnViewAllStaffReq.setText("View All Requests");
        btnViewAllStaffReq.setToolTipText("View all requests from staff");
        btnViewAllStaffReq.setBorderPainted(false);
        btnViewAllStaffReq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewAllStaffReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllStaffReqActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewAllStaffReq);
        btnViewAllStaffReq.setBounds(110, 170, 150, 40);

        btnViewComplStaffRequests.setBackground(new java.awt.Color(254, 212, 29));
        btnViewComplStaffRequests.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnViewComplStaffRequests.setText("View Complete Requests");
        btnViewComplStaffRequests.setToolTipText("View completed requests from staff");
        btnViewComplStaffRequests.setBorderPainted(false);
        btnViewComplStaffRequests.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewComplStaffRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewComplStaffRequestsActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewComplStaffRequests);
        btnViewComplStaffRequests.setBounds(280, 170, 190, 40);

        jButton1.setBackground(new java.awt.Color(254, 212, 29));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Generate Report");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(750, 520, 180, 40);

        btnViewIncomStaffRequests.setBackground(new java.awt.Color(254, 212, 29));
        btnViewIncomStaffRequests.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnViewIncomStaffRequests.setText("View Incomplete Requests");
        btnViewIncomStaffRequests.setToolTipText("View incomplete requests from staff");
        btnViewIncomStaffRequests.setBorderPainted(false);
        btnViewIncomStaffRequests.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewIncomStaffRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewIncomStaffRequestsActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewIncomStaffRequests);
        btnViewIncomStaffRequests.setBounds(490, 170, 220, 40);

        lDay.setText("Day");
        getContentPane().add(lDay);
        lDay.setBounds(730, 120, 19, 14);

        spnDay.setModel(new javax.swing.SpinnerNumberModel(1, 0, 31, 1));
        getContentPane().add(spnDay);
        spnDay.setBounds(730, 140, 50, 20);

        btnSortByDate.setBackground(new java.awt.Color(254, 212, 29));
        btnSortByDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSortByDate.setText("Sort By Date");
        btnSortByDate.setBorderPainted(false);
        btnSortByDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortByDateActionPerformed(evt);
            }
        });
        getContentPane().add(btnSortByDate);
        btnSortByDate.setBounds(730, 170, 190, 40);

        lYear.setText("Year");
        getContentPane().add(lYear);
        lYear.setBounds(850, 120, 22, 14);

        lMonth.setText("Month");
        getContentPane().add(lMonth);
        lMonth.setBounds(790, 120, 30, 14);

        spnYear.setModel(new javax.swing.SpinnerNumberModel(2000, 2000, 2020, 1));
        getContentPane().add(spnYear);
        spnYear.setBounds(840, 140, 80, 20);

        spnMonth.setModel(new javax.swing.SpinnerNumberModel(2, 0, 12, 1));
        getContentPane().add(spnMonth);
        spnMonth.setBounds(790, 140, 40, 20);

        tblStaffRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request", "Staff Name", "Day", "Month", "Year"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStaffRequests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStaffRequestsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStaffRequests);
        if (tblStaffRequests.getColumnModel().getColumnCount() > 0) {
            tblStaffRequests.getColumnModel().getColumn(0).setResizable(false);
            tblStaffRequests.getColumnModel().getColumn(1).setResizable(false);
            tblStaffRequests.getColumnModel().getColumn(2).setResizable(false);
            tblStaffRequests.getColumnModel().getColumn(3).setResizable(false);
            tblStaffRequests.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 240, 820, 280);

        btnBackLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnBackLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnBackLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        btnBackLogout.setToolTipText("Back");
        btnBackLogout.setBorder(null);
        btnBackLogout.setBorderPainted(false);
        btnBackLogout.setContentAreaFilled(false);
        btnBackLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackLogoutMouseClicked(evt);
            }
        });
        btnBackLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnBackLogout);
        btnBackLogout.setBounds(950, 10, 31, 31);

        btnMinimize.setBackground(new java.awt.Color(255, 255, 255));
        btnMinimize.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        btnMinimize.setToolTipText("Minimize");
        btnMinimize.setBorder(null);
        btnMinimize.setBorderPainted(false);
        btnMinimize.setContentAreaFilled(false);
        btnMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(btnMinimize);
        btnMinimize.setBounds(910, 10, 31, 31);

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        btnExit.setToolTipText("Exit");
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(980, 10, 50, 30);

        frameMove.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                frameMoveMouseDragged(evt);
            }
        });
        frameMove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                frameMoveMousePressed(evt);
            }
        });
        getContentPane().add(frameMove);
        frameMove.setBounds(4, 0, 900, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/orderMng.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1031, 637);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackLogoutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackLogoutMouseClicked

    private void btnBackLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackLogoutActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);;
        this.dispose();
    }//GEN-LAST:event_btnBackLogoutActionPerformed

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        int selection = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Please Note", JOptionPane.INFORMATION_MESSAGE);
        if (selection == JOptionPane.YES_OPTION) {
            Admin.UpdateAdminLoggedIn(AdminLogin.activeUser, 0);
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnViewIncomStaffRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewIncomStaffRequestsActionPerformed
        ArrayList<StaffRequest> staffRequests = StaffRequest.getStaffRequests(StaffRequestHandler.requestType.Incomplete, 0);
        populateTable(staffRequests);

    }//GEN-LAST:event_btnViewIncomStaffRequestsActionPerformed

    private void btnViewAllStaffReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllStaffReqActionPerformed
        ArrayList<StaffRequest> staffRequests = StaffRequest.getStaffRequests(StaffRequestHandler.requestType.All, 0);
        populateTable(staffRequests);
    }//GEN-LAST:event_btnViewAllStaffReqActionPerformed

    private void btnViewComplStaffRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewComplStaffRequestsActionPerformed
        ArrayList<StaffRequest> staffRequests = StaffRequest.getStaffRequests(StaffRequestHandler.requestType.Complete, 0);
        populateTable(staffRequests);
    }//GEN-LAST:event_btnViewComplStaffRequestsActionPerformed

    private void tblStaffRequestsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStaffRequestsMouseClicked
        //Get selected value
        //Send object to update form.
        DefaultTableModel dmodel = (DefaultTableModel) tblStaffRequests.getModel();
        StaffRequest curRequest = new StaffRequest();
        int CurrentPackage
                = ((int) tblStaffRequests.getValueAt(
                        tblStaffRequests.getSelectedRow(), 0));
        //check that it is an unmanaged package
        ArrayList<StaffRequest> staffRequests = StaffRequest.getStaffRequests(StaffRequestHandler.requestType.All, 0);
        boolean checkIncomplete = false;
        for (StaffRequest st : staffRequests) {
            if (CurrentPackage == st.getRequestNr() && st.getComplete() == 0) {
                checkIncomplete = true;
            }
        }
        if (checkIncomplete) {
            int selection = JOptionPane.showConfirmDialog(null, "Do you want to handle request " + CurrentPackage,
                    "Please Note", JOptionPane.INFORMATION_MESSAGE);
            if (selection == JOptionPane.YES_OPTION) {
                for (StaffRequest request : staffRequests) {
                    if (request.getRequestNr() == CurrentPackage) {
                        curRequest = request;
                    }
                }
                //new update page object
                AdminOrderCompletion newAdminOrderCompletion = new AdminOrderCompletion(curRequest);
                newAdminOrderCompletion.setVisible(true);;
                this.dispose();
            }
        }
    }//GEN-LAST:event_tblStaffRequestsMouseClicked

    private void btnSortByDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortByDateActionPerformed
        ArrayList<StaffRequest> staffRequests = StaffRequest.getStaffRequests(StaffRequestHandler.requestType.All, 0);
        ArrayList<StaffRequest> holder = new ArrayList<>();
        boolean dayZero = ((int) spnDay.getValue() == 0);
        boolean monthZero = ((int) spnMonth.getValue() == 0);
        for (StaffRequest sr : staffRequests) {
            if (dayZero && !monthZero) {
                if (sr.getRequestDate().getMonth() + 1 == (int) spnMonth.getValue()
                        && sr.getRequestDate().getYear() + 1900 == (int) spnYear.getValue()) {
                    holder.add(sr);
                }
            } else if (!dayZero && !monthZero) {
                if (sr.getRequestDate().getMonth() + 1 == (int) spnMonth.getValue()
                        && sr.getRequestDate().getDate() == (int) spnDay.getValue()
                        && sr.getRequestDate().getYear() + 1900 == (int) spnYear.getValue()) {
                    holder.add(sr);
                }
            } else {
                if (sr.getRequestDate().getYear() + 1900 == (int) spnYear.getValue()) {
                    holder.add(sr);
                }
            }
        }
        populateTable(holder);
    }//GEN-LAST:event_btnSortByDateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList<Staff> allStaff = (new Staff()).getStaff(StaffHandler.staffType.All);
        ArrayList<Stock> allStock = (new Stock()).getStock();
        RequestDetails dets = new RequestDetails();
        
        ArrayList<StaffRequest> staffRequests
                = StaffRequest.getStaffRequests(StaffRequestHandler.requestType.All, 0);
        ArrayList<StaffRequest> holder = new ArrayList<>();
        //get spinners values 
        int day = (int) spnDay.getValue();
        int month = (int) spnMonth.getValue();
        int Year = (int) spnYear.getValue();
        //set Interval
        String dateInterval = "";
        boolean dayZero = (day == 0);
        boolean monthZero = (month == 0);
        for (StaffRequest sr : staffRequests) {
            if (dayZero && !monthZero) {
                dateInterval = new DateFormatSymbols().getMonths()[month - 1];
                if (sr.getRequestDate().getMonth() + 1 == (int) spnMonth.getValue()
                        && sr.getRequestDate().getYear() + 1900 == (int) spnYear.getValue()) {
                    holder.add(sr);
                }
            } else if (!dayZero && !monthZero) {
                dateInterval = Year + "-" + month + "-" + day;
                if (sr.getRequestDate().getMonth() + 1 == (int) spnMonth.getValue()
                        && sr.getRequestDate().getDate() == (int) spnDay.getValue()
                        && sr.getRequestDate().getYear() + 1900 == (int) spnYear.getValue()) {
                    holder.add(sr);
                }
            } else {
                dateInterval = "" + Year;
                if (sr.getRequestDate().getYear() + 1900 == (int) spnYear.getValue()) {
                    holder.add(sr);
                }
            }
        }
        if (holder.size() == 0) {
            JOptionPane.showMessageDialog(null, "The selection is empty no report can be made");
        } else {

            //Get current inventory
            //allStock;
            //get current purchase orders
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/mm/dd");
            Date d = new Date();
            String output = String.format(
                    "==================================================================================================\n"
                    + "           STAFF REQUEST REPORT            " + sdf.format(d) + "                          =\n"
                    + "==================================================================================================\n"
                    + "The following tables shows all the staffs' request made for %s :\n",dateInterval);
//                    + "Request %s by %s on %s_______________________________________________________________________________________________\n"
//                    + "|%5s|%21s|%13s|%21s|%10s|%8s|%10s|\n"
//                    + "________________________________________________________________________________________________\n",
//                     dateInterval,"Request ID", "Staff Name", "Date", "Category", "Price", "Quantity", "Entry Date");
            for (StaffRequest sr : holder) {
                output+=String.format("Request %s by USER %s on %s\n"
                        + "____________________________________________________________________________________\n"
                        + "|%19s|%19s|%19s|%19s|\n",sr.getRequestNr(),sr.getStaffID(),sr.getRequestDate(),"ProductName","Manufacturer","Category","Quantity");
                ArrayList<RequestDetails> recDetails = RequestDetails.getRequestDetails(StaffRequestHandler.requestType.All, sr.getStaffID(), sr.getRequestNr());
                for (RequestDetails rd : recDetails) {
                    output+= String.format("|%19s|%19s|%19s|%19s|\n",
                            (rd.getProductName().length()>19)?rd.getProductName().substring(0,18):rd.getProductName(),
                            (rd.getManufacturer().length()>19)?rd.getManufacturer().substring(0,18):rd.getManufacturer(),
                            (rd.getCategory().length()>19)?rd.getCategory().substring(0,18):rd.getCategory(),
                            rd.getQuantity() );
                }
            }
            output+= "____________________________________________________________________________________\n";
            // make pretty report
            JFileChooser f = new JFileChooser();
            f.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            f.showSaveDialog(null);
            String directory = (String) (f.getCurrentDirectory()).getPath();
            directory += "\\RequestHistory Report";
            Reporter rep = new Reporter(output);
            BCSerializer ser = new BCSerializer(output);
            rep.saveReport(directory);
            ser.Serialize(directory);
            // export ass xml
            // export as serialised
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    int xMouse;
    int yMouse;
    private void frameMoveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameMoveMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);

    }//GEN-LAST:event_frameMoveMouseDragged

    private void frameMoveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameMoveMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_frameMoveMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOrders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackLogout;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JButton btnSortByDate;
    private javax.swing.JButton btnViewAllStaffReq;
    private javax.swing.JButton btnViewComplStaffRequests;
    private javax.swing.JButton btnViewIncomStaffRequests;
    private javax.swing.JLabel frameMove;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lDay;
    private javax.swing.JLabel lMonth;
    private javax.swing.JLabel lYear;
    private javax.swing.JSpinner spnDay;
    private javax.swing.JSpinner spnMonth;
    private javax.swing.JSpinner spnYear;
    private javax.swing.JTable tblStaffRequests;
    // End of variables declaration//GEN-END:variables
}
