/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;
//t

import BusinessLayerPackage.Category;
import BusinessLayerPackage.ICategory;
import BusinessLayerPackage.IStaff;
import BusinessLayerPackage.IStock;
import BusinessLayerPackage.SingleRegistry;
import BusinessLayerPackage.Staff;
import BusinessLayerPackage.Stock;
import BusinessLayerPackage.sortQty;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.rmi.AccessException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;

/**
 *
 * @author User
 */
public class StaffItems extends javax.swing.JFrame {

    /**
     * Creates new form Administrator
     */
    public StaffItems() {
        try {
            initComponents();
            //
            ICategory categoryImp = (ICategory) SingleRegistry.getInstance().getRegistry().lookup("category");
            for (Category cat : categoryImp.getCategories()) {
                //fill with all possible names
                cmboCategory.addItem(cat.getName());
            }
            //
            IStock stockImp = (IStock) SingleRegistry.getInstance().getRegistry().lookup("stock");
            allStock = stockImp.getStock();
            populateTable(allStock);
            //event listener for sorting on column headers
            JTableHeader header = tblInventory.getTableHeader();
            //using built in function
            tblInventory.setAutoCreateRowSorter(true);
            //using comparator
            //header.addMouseListener(new headerSortMouseListener(tblInventory));
//        JTable dmodel = new JTable(tblInventory.getModel());
//        dmodel.getTableHeader().addMouseListener(new MouseAdapter () { 
//            @Override
//            public void mouseClicked(MouseEvent e) {
//                int colSelected = dmodel.columnAtPoint(e.getPoint());
//                JOptionPane.showMessageDialog(null,colSelected);
//            }
//            
//        });
        } catch (NotBoundException ex) {
            Logger.getLogger(StaffItems.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(StaffItems.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private ArrayList<Stock> allStock;

    private void populateTable(ArrayList<Stock> stockList) {

        DefaultTableModel dmodel = (DefaultTableModel) tblInventory.getModel();
        Object[] row = new Object[5];
        //clearTable
        dmodel.setRowCount(0);
        if (stockList.size() > 0) {
            for (Stock stc : stockList) {
                row[0] = stc.getStockID();
                row[1] = stc.getProductName();
                row[2] = stc.getManufacturer();
                row[3] = stc.getCategory();
                row[4] = stc.getQuantity();
                dmodel.addRow(row);
            }
        } else {
            JOptionPane.showMessageDialog(null, "There is no Data that matches your search result", "Attention", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmboCategory = new javax.swing.JComboBox<>();
        btnStaffViewAllStock = new javax.swing.JButton();
        txtSearchStock = new javax.swing.JTextField();
        btnSearchStock = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();
        btnExit = new javax.swing.JButton();
        btnBackLogout = new javax.swing.JButton();
        btnMinimize = new javax.swing.JButton();
        btnChoose = new javax.swing.JButton();
        btnSortQty = new javax.swing.JButton();
        btnFilterCategory = new javax.swing.JButton();
        rbProdName = new javax.swing.JRadioButton();
        rbCategory = new javax.swing.JRadioButton();
        frameMove = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1029, 637));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        cmboCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category" }));
        cmboCategory.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(cmboCategory);
        cmboCategory.setBounds(240, 160, 210, 30);

        btnStaffViewAllStock.setBackground(new java.awt.Color(254, 212, 29));
        btnStaffViewAllStock.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnStaffViewAllStock.setText("View All");
        btnStaffViewAllStock.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 212, 29), 1, true));
        btnStaffViewAllStock.setBorderPainted(false);
        btnStaffViewAllStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStaffViewAllStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffViewAllStockActionPerformed(evt);
            }
        });
        getContentPane().add(btnStaffViewAllStock);
        btnStaffViewAllStock.setBounds(100, 120, 130, 31);

        txtSearchStock.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtSearchStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchStockActionPerformed(evt);
            }
        });
        getContentPane().add(txtSearchStock);
        txtSearchStock.setBounds(660, 120, 202, 36);

        btnSearchStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/searchIcon.png"))); // NOI18N
        btnSearchStock.setBorderPainted(false);
        btnSearchStock.setContentAreaFilled(false);
        btnSearchStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStockActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchStock);
        btnSearchStock.setBounds(880, 110, 46, 49);

        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ProductName", "Manufacturer", "Category", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInventory.setColumnSelectionAllowed(true);
        tblInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInventoryMouseClicked(evt);
            }
        });
        tblInventory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblInventoryKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblInventory);
        tblInventory.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblInventory.getColumnModel().getColumnCount() > 0) {
            tblInventory.getColumnModel().getColumn(0).setResizable(false);
            tblInventory.getColumnModel().getColumn(1).setResizable(false);
            tblInventory.getColumnModel().getColumn(2).setResizable(false);
            tblInventory.getColumnModel().getColumn(3).setResizable(false);
            tblInventory.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 220, 832, 270);

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        btnExit.setToolTipText("Exit");
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(980, 10, 50, 30);

        btnBackLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnBackLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnBackLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        btnBackLogout.setToolTipText("Back");
        btnBackLogout.setBorder(null);
        btnBackLogout.setBorderPainted(false);
        btnBackLogout.setContentAreaFilled(false);
        btnBackLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackLogoutMouseClicked(evt);
            }
        });
        btnBackLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnBackLogout);
        btnBackLogout.setBounds(950, 10, 31, 31);

        btnMinimize.setBackground(new java.awt.Color(255, 255, 255));
        btnMinimize.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        btnMinimize.setToolTipText("Minimize");
        btnMinimize.setBorder(null);
        btnMinimize.setBorderPainted(false);
        btnMinimize.setContentAreaFilled(false);
        btnMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
        });
        getContentPane().add(btnMinimize);
        btnMinimize.setBounds(910, 10, 31, 31);

        btnChoose.setBackground(new java.awt.Color(254, 212, 29));
        btnChoose.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnChoose.setText("Choose Item");
        btnChoose.setBorderPainted(false);
        btnChoose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChoose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChooseMouseClicked(evt);
            }
        });
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });
        getContentPane().add(btnChoose);
        btnChoose.setBounds(780, 520, 150, 30);

        btnSortQty.setBackground(new java.awt.Color(254, 212, 29));
        btnSortQty.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnSortQty.setText("Sort by Quantity");
        btnSortQty.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 212, 29), 1, true));
        btnSortQty.setBorderPainted(false);
        btnSortQty.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSortQty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSortQtyMouseClicked(evt);
            }
        });
        btnSortQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortQtyActionPerformed(evt);
            }
        });
        getContentPane().add(btnSortQty);
        btnSortQty.setBounds(640, 520, 130, 31);

        btnFilterCategory.setBackground(new java.awt.Color(254, 212, 29));
        btnFilterCategory.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnFilterCategory.setText("Filter by Category");
        btnFilterCategory.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 212, 29), 1, true));
        btnFilterCategory.setBorderPainted(false);
        btnFilterCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFilterCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFilterCategoryMouseClicked(evt);
            }
        });
        btnFilterCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnFilterCategory);
        btnFilterCategory.setBounds(100, 160, 130, 31);

        rbProdName.setBackground(new java.awt.Color(255, 255, 255));
        rbProdName.setText("Product Name");
        rbProdName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbProdNameMouseClicked(evt);
            }
        });
        getContentPane().add(rbProdName);
        rbProdName.setBounds(660, 160, 120, 23);

        rbCategory.setBackground(new java.awt.Color(255, 255, 255));
        rbCategory.setText("Category");
        rbCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbCategoryMouseClicked(evt);
            }
        });
        getContentPane().add(rbCategory);
        rbCategory.setBounds(780, 160, 120, 23);

        frameMove.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                frameMoveMouseDragged(evt);
            }
        });
        frameMove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                frameMoveMousePressed(evt);
            }
        });
        getContentPane().add(frameMove);
        frameMove.setBounds(4, 0, 900, 40);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/InventoryBG.png"))); // NOI18N
        getContentPane().add(BG);
        BG.setBounds(0, 0, 1030, 637);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        int selection = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Please Note", JOptionPane.INFORMATION_MESSAGE);
        if (selection == JOptionPane.YES_OPTION) {
            try {
                IStaff staffImp = (IStaff) SingleRegistry.getInstance().getRegistry().lookup("staff");
                staffImp.updateStaffLoggedIn(StaffLogin.activeUser.getUsername(), 0);
                System.exit(0);
            } catch (RemoteException ex) {
                Logger.getLogger(StaffItems.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(StaffItems.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnBackLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackLogoutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackLogoutMouseClicked

    private void btnBackLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackLogoutActionPerformed
        StaffMenu staffMenu = new StaffMenu();
        staffMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackLogoutActionPerformed

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void txtSearchStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchStockActionPerformed

    private void btnSearchStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStockActionPerformed
        //Iterate and search for specific stock
        String input = txtSearchStock.getText().toLowerCase();

        ArrayList<Stock> newListStock = new ArrayList<Stock>();
        if (!input.isEmpty()) {
            if (rbProdName.isSelected()) {
                for (Stock stock : allStock) {
                    if ((stock.getProductName().toLowerCase().contains(input))) {
                        newListStock.add(stock);
                    }
                }
                populateTable(newListStock);
            } else if (rbCategory.isSelected()) {
                for (Stock stock : allStock) {
                    if (stock.getCategory().toLowerCase().contains(input)) {
                        newListStock.add(stock);
                    }
                }
                populateTable(newListStock);
            } else {
                JOptionPane.showMessageDialog(null, "Please select a Search Criteria");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Please enter a keyword for the search", "Attention", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchStockActionPerformed

    private void btnStaffViewAllStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffViewAllStockActionPerformed
        populateTable(allStock);
    }//GEN-LAST:event_btnStaffViewAllStockActionPerformed

    private void tblInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInventoryMouseClicked

    }//GEN-LAST:event_tblInventoryMouseClicked

    private void tblInventoryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblInventoryKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblInventoryKeyPressed

    public static Stock chosenItem;

    private void btnChooseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChooseMouseClicked
        try {
            int stockID = (int) tblInventory.getValueAt(tblInventory.getSelectedRow(), 0);
            //
            int selection = JOptionPane.showConfirmDialog(null, "Are you sure you want request this item?", "Request ", JOptionPane.INFORMATION_MESSAGE);
            if (selection == JOptionPane.YES_OPTION) {
                IStock stockImp = (IStock) SingleRegistry.getInstance().getRegistry().lookup("stock");
                chosenItem = stockImp.getStockItem(stockID);
                //
                RequestItems requestItem = new RequestItems();
                requestItem.setVisible(true);
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please select a valid Item to Request");
        }
    }//GEN-LAST:event_btnChooseMouseClicked

    private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChooseActionPerformed

    private void btnFilterCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFilterCategoryActionPerformed

    private void btnSortQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSortQtyActionPerformed

    private void btnFilterCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFilterCategoryMouseClicked
        if (cmboCategory.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Please select a valid Category");
        } else {
//            String val = (String) cmboCategory.getSelectedItem();
//            allStock = Stock.getStockByCategory(val);
//            populateTable(allStock);
            ArrayList<Stock> newListStock = new ArrayList<Stock>();
            for (Stock stock : allStock) {
                if (stock.getCategory().contains(cmboCategory.getSelectedItem().toString())) {
                    newListStock.add(stock);
                }
            }
            populateTable(newListStock);
        }
    }//GEN-LAST:event_btnFilterCategoryMouseClicked

    private void rbProdNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbProdNameMouseClicked
        rbCategory.setSelected(false);
    }//GEN-LAST:event_rbProdNameMouseClicked

    private void rbCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbCategoryMouseClicked
        rbProdName.setSelected(false);
    }//GEN-LAST:event_rbCategoryMouseClicked

    private void btnSortQtyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSortQtyMouseClicked
        Collections.sort(allStock, new sortQty());
        populateTable(allStock);
    }//GEN-LAST:event_btnSortQtyMouseClicked

    int xMouse;
    int yMouse;
    private void frameMoveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameMoveMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);

    }//GEN-LAST:event_frameMoveMouseDragged

    private void frameMoveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameMoveMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_frameMoveMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffItems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton btnBackLogout;
    private javax.swing.JButton btnChoose;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFilterCategory;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JButton btnSearchStock;
    private javax.swing.JButton btnSortQty;
    private javax.swing.JButton btnStaffViewAllStock;
    private javax.swing.JComboBox<String> cmboCategory;
    private javax.swing.JLabel frameMove;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbCategory;
    private javax.swing.JRadioButton rbProdName;
    private javax.swing.JTable tblInventory;
    private javax.swing.JTextField txtSearchStock;
    // End of variables declaration//GEN-END:variables
}
